config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :users
      resources :patients
      resources :appointment_statuses
      resources :doctor_categories
      resources :appointments
      resources :doctors

      root to: "users#index"
    end
  get 'home/index'
  resources :patients
  resources :doctors
  resources :appointments
  get '/appointments/new/:doctor_id' => 'appointments#new'
  # get '/appointments/:id/edit' => 'appointments#edit'
  # post '/appointments' => 'appointments#create'
  # patch '/appointments/:id' => 'appointments#update'
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  get 'doctors_search/:doctor_category_id' => 'patients#doctors_search'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "home#index"
end

app/models/patient.rb
class Patient < ApplicationRecord
  has_many :appointments
  has_many :doctors, through: :appointments
  belongs_to :user
end

app/controllers/admin/patients_controller.rb
module Admin
  class PatientsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: %i[ show edit update destroy ]

  # GET /patients or /patients.json
  def index
    @patients = Patient.all
  end

  # GET /patients/1 or /patients/1.json
  def show
    query = "SELECT u.name as d_name, dc.name as dc_name, a.appointment_date, aps.name as aps_name, a.recomendations
      FROM appointments a
      inner join appointment_statuses aps on a.appointment_status_id=aps.id
      inner join doctors d on a.doctor_id=d.id
      inner join doctor_categories dc on d.doctor_category_id=dc.id
      inner join users u on d.user_id=u.id
      WHERE a.patient_id=?"
    @doctor_categories = DoctorCategory.all
    @doctors_by_category = Doctor.select('users.name as u_name, doctor_categories.name as dc_name, doctors.id as d_id').joins(:doctor_category, :user).all
    @appointments = Appointment.find_by_sql( [query, @patient.id] )
  end

  def doctors_search
    if params[:doctor_category_id].present?
      @doctors_by_category = Doctor.select('users.name as u_name, doctor_categories.name as dc_name, doctors.id as d_id').joins(:doctor_category, :user).where("doctor_category_id = ?", params[ :doctor_category_id ])
    else
      @doctors_by_category = Doctor.select('users.name as u_name, doctor_categories.name as dc_name, doctors.id as d_id').joins(:doctor_category, :user).all
    end
    respond_to do |format|
      format.js {render layout: false} # Add this line to you respond_to block
    end
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients or /patients.json
  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to patient_url(@patient), notice: "Patient was successfully created." }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1 or /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to patient_url(@patient), notice: "Patient was successfully updated." }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1 or /patients/1.json
  def destroy
    @patient.destroy

    respond_to do |format|
      format.html { redirect_to patients_url, notice: "Patient was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def patient_params
      params.fetch(:patient, {})
    end
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/_doctors_by_category.html.erb
  <% @doctors_by_category.each do |d| %>
  <div class="list-group">
    <div class="d-flex w-400 justify-content-between">
      <h5 class="mb-1"><%= d.u_name %></h5>
      <small><%= button_to "Appointment", '/appointments/new/'+d.d_id.to_s, method: :get, class: "btn btn-primary" %></small>
    </div>
    <p class="mb-1"><%= d.dc_name %></p>
  </div>
  <% end %>

app/views/patients/_form.html.erb
<%= form_with(model: patient) do |form| %>
  <% if patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
        <% patient.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/patients/doctors_search.js.erb
Rails.$('#doctors_by_category')[0].innerHTML = ("<%= j (render partial: 'patients/doctors_by_category') %>")

app/views/patients/edit.html.erb
<h1>Editing Patient</h1>

<%= render 'form', patient: @patient %>

<%= link_to 'Show', @patient %> |
<%= link_to 'Back', patients_path %>

app/views/patients/show.html.erb
<h1><%= current_user.name %></h1>

<div class="d-flex align-items-start">
  <div class="nav flex-column nav-pills me-3" id="v-pills-tab" role="tablist" aria-orientation="vertical">
    <button class="nav-link active" id="v-pills-profile-tab" data-bs-toggle="pill" data-bs-target="#v-pills-profile" type="button" role="tab" aria-controls="v-pills-profile" aria-selected="true">Profile</button>
    <button class="nav-link" id="v-pills-doctors-tab" data-bs-toggle="pill" data-bs-target="#v-pills-doctors" type="button" role="tab" aria-controls="v-pills-doctors" aria-selected="false">Doctors</button>
    <button class="nav-link" id="v-pills-appointments-tab" data-bs-toggle="pill" data-bs-target="#v-pills-appointments" type="button" role="tab" aria-controls="v-pills-appointments" aria-selected="false">Appointments</button>
  </div>
  <div class="tab-content" id="v-pills-tabContent" style="width: 500px">
    <div class="tab-pane fade show active" id="v-pills-profile" role="tabpanel" aria-labelledby="v-pills-profile-tab">
      <%= link_to "Edit user profile", edit_user_registration_path %>
    </div>
    <div class="tab-pane fade" id="v-pills-doctors" role="tabpanel" aria-labelledby="v-pills-doctors-tab">
      <div data-controller="doctors_search">
        <%= form_with model: @patients, local: false do |f| %>
          <%= f.collection_select :doctor_category_id,
            DoctorCategory.all,
            :id,
            :name,
            { prompt: 'Select doctors category' },
            { class: 'form-select', remote: true } %>
        <% end %>
      </div>
      <div id="doctors_by_category">
        <%= render partial: "doctors_by_category" %>
      </div>
    </div>
    <div class="tab-pane fade" id="v-pills-appointments" role="tabpanel" aria-labelledby="v-pills-appontments-tab">
      <% @appointments.each do |a| %>
      <div class="list-group">
        <div class="d-flex w-400 justify-content-between">
          <h5 class="mb-1">Appointment to <%= a.d_name %> (<%= a.dc_name %>)</h5>
          <small><%= a.appointment_date.strftime("Appointed to %F %H:%M") %></small>
        </div>
        <p class="mb-1"><% if a.recomendations.nil? %>
          No recomendations
          <% else %>
          <%= a.recomendations %>
          <% end %></p>
        <small>Appointments status: <%= a.aps_name %></small>
      </div>
      <% end %>
    </div>
  </div>
</div>