config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :users
      resources :patients
      resources :appointment_statuses
      resources :doctor_categories
      resources :appointments
      resources :doctors

      root to: "users#index"
    end
  get 'home/index'
  resources :patients
  resources :doctors
  resources :appointments
  get '/appointments/new/:doctor_id' => 'appointments#new'
  # get '/appointments/:id/edit' => 'appointments#edit'
  # post '/appointments' => 'appointments#create'
  # patch '/appointments/:id' => 'appointments#update'
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  get 'doctors_search/:doctor_category_id' => 'patients#doctors_search'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "home#index"
end

app/models/doctor.rb
class Doctor < ApplicationRecord

  has_many :appointments
  has_many :patients, through: :appointments
  belongs_to :user
  belongs_to :doctor_category

end

app/controllers/admin/doctors_controller.rb
module Admin
  class DoctorsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :set_doctor, only: %i[ show edit update destroy ]

  # GET /doctors or /doctors.json
  def index
    @doctors = Doctor.all
  end

  # GET /doctors/1 or /doctors/1.json
  def show
    query = "SELECT a.id, u.name as p_name, a.appointment_date, aps.name as aps_name, a.recomendations
      FROM appointments a
      inner join appointment_statuses aps on a.appointment_status_id=aps.id
      inner join patients p on a.patient_id=p.id
      inner join users u on p.user_id=u.id
      WHERE a.doctor_id=?"
    @doctor_categories = DoctorCategory.all
    @current_category = DoctorCategory.find(@doctor.doctor_category_id)
    @appointments = Appointment.find_by_sql( [query, @doctor.id] )
  end

  # GET /doctors/new
  def new
    @doctor = Doctor.new
  end

  # GET /doctors/1/edit
  def edit
  end

  # POST /doctors or /doctors.json
  def create
    @doctor = Doctor.new(doctor_params)

    respond_to do |format|
      if @doctor.save
        format.html { redirect_to doctor_url(@doctor), notice: "Doctor was successfully created." }
        format.json { render :show, status: :created, location: @doctor }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /doctors/1 or /doctors/1.json
  def update
    respond_to do |format|
      if @doctor.update(doctor_params)
        format.html { redirect_to doctor_url(@doctor), notice: "Doctor was successfully updated." }
        format.json { render :show, status: :ok, location: @doctor }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /doctors/1 or /doctors/1.json
  def destroy
    @doctor.destroy

    respond_to do |format|
      format.html { redirect_to doctors_url, notice: "Doctor was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_doctor
      @doctor = Doctor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def doctor_params
      params.fetch(:doctor, {}).permit(:doctor_category_id)
    end
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/views/doctors/_form.html.erb
<%= form_with(model: doctor) do |form| %>
  <% if doctor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(doctor.errors.count, "error") %> prohibited this doctor from being saved:</h2>

      <ul>
        <% doctor.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/doctors/edit.html.erb
<h1>Editing Doctor</h1>

<%= render 'form', doctor: @doctor %>

<%= link_to 'Show', @doctor %> |
<%= link_to 'Back', doctors_path %>

app/views/doctors/show.html.erb
<h1><%= current_user.name %> (<%= @current_category.name %>)</h1>

<div class="d-flex align-items-start">
  <div class="nav flex-column nav-pills me-3" id="v-pills-tab" role="tablist" aria-orientation="vertical">
    <button class="nav-link active" id="v-pills-profile-tab" data-bs-toggle="pill" data-bs-target="#v-pills-profile" type="button" role="tab" aria-controls="v-pills-profile" aria-selected="true">Profile</button>
    <button class="nav-link" id="v-pills-appointments-tab" data-bs-toggle="pill" data-bs-target="#v-pills-appointments" type="button" role="tab" aria-controls="v-pills-appointments" aria-selected="false">Appointments</button>
  </div>
  <div class="tab-content" id="v-pills-tabContent" style="width: 500px">
    <div class="tab-pane fade show active" id="v-pills-profile" role="tabpanel" aria-labelledby="v-pills-profile-tab">
      <%= link_to "Edit user profile", edit_user_registration_path %>
      <hr>
      <%= form_with model: @doctor do |f| %>
        <%= f.label 'Change your category.', class: "form-label" %><br />
        <%= f.collection_select :doctor_category_id,
          DoctorCategory.all,
          :id,
          :name,
          { prompt: 'Change your category.' },
          { class: 'form-select' } %>
          <%= f.submit "Change" %>
      <% end %>
    </div>
    <div class="tab-pane fade" id="v-pills-appointments" role="tabpanel" aria-labelledby="v-pills-appontments-tab">
      <% @appointments.each do |a| %>
      <div class="list-group">
        <div class="d-flex w-400 justify-content-between">
          <h5 class="mb-1">Appointment to <%= a.p_name %></h5>
          <small><%= a.appointment_date.strftime("Appointed to %F %H:%M") %></small>
        </div>
        <div class="d-flex w-400 justify-content-between">
          <p class="mb-1"><% if a.recomendations.nil? %>
            No recomendations
            <% else %>
            <%= a.recomendations %>
            <% end %></p>
          <p><%= button_to "Add recomendation", '/appointments/'+a.id.to_s+'/edit', method: :get, class: "btn btn-primary" %></p>
          </div>
        <small>Appointments status: <%= a.aps_name %></small>
      </div>
      <% end %>
    </div>
  </div>
</div>